name: Deploy to firebase

on:
  push:
    branches:
      - master
env:
  VITE_APY_KEY: ${{ secrets.VITE_APY_KEY }}
  VITE_API_DOMAIN: ${{ vars.VITE_API_DOMAIN }}
  VITE_PROJECT_ID: ${{ vars.VITE_PROJECT_ID }}
  VITE_STORAGE_BUCKET: ${{ vars.VITE_STORAGE_BUCKET }}
  VITE_MESSAGE_SENDER_ID: ${{ vars.VITE_MESSAGE_SENDER_ID }}
  VITE_APP_ID: ${{ vars.VITE_APP_ID }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Setup the code
        run: npm install
      - uses: hmarr/debug-action@v2
      - name: Build then app
        run: npm run build
      - name: Deploy to Firebase
        uses: mohammed-atif/firebase-publish-react@v1.0
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
